### ISSUE TITLE
What license does this project have

### ISSUE THREAD

**Issue by ShowerBook** [ThePieMonster/WaniKanify-2.0#10]
Hello,

I was wondering what license did this project have because I wanted to fork it and substantially change it to fit my needs (Firefox compatibility and some other things) and publish it under another name to avoid confusion with this main project (while crediting it)

**Comment by ThePieMonster** [comment]
This project is published without a license on purpose. As the code has been contributed by multiple individuals over the years, re-publishing under a new name (especially while this project is actively maintained) is forbidden. 

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

That being the case, I have had multiple requests to port this over to Firefox. I can't speak on behalf of the edits you wish to make, but I will look into porting this over to that browser very soon and you are more than welcome to contribute to this move. Feel free to reach out to the developer email address if you would like more information on the move.
