### ISSUE TITLE
Error 400 Bad Request due to Url length

### ISSUE THREAD

**Issue by domi2120** [ThePieMonster/WaniKanify-2.0#3]
In Background.js line 131 The Vocabulary is loaded with an url parameter for the ids  that need to be loaded to limit the data requested from the Wanikani Api. This can result in an extremely long url (due to the querystring) which will result in a bad Request (400) at more than 10277 characters. A possible fix would be to batch the request, or to load all vocabulary and filter clientside.

**Comment by ThePieMonster** [comment]
Thanks for the reply. Will look into what you mentioned here. There is some pagination going on and it looks like the [api](https://docs.api.wanikani.com/20170710/#Pagination) is restricting it to 1000 items. I have not been able to replicated the error on any of the machines I have though. Just pushed out 2.0.3 update that has some better logging and will see what kind of user responses I get.
